.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC
    ;TO FIND THE MAXIMUM NUMBER 
    ;PROMPT USER
    
    MOV AH,2
    MOV DL,':'
    INT 21H
    ;TAKE ONE INPUT
    MOV AH,1
    INT 21H
    MOV CL,AL ;SAVE THE FIRST NUMBER
    
    ;PROMPT USER
    
    MOV AH,2
    MOV DL,':'
    INT 21H
      
      ;SECOND INPUT
     MOV AH,1
    INT 21H 
    
    CMP AL,CL;(SUB AL,CL IS SAME BUT CMP DOES NOT SAVE THE SUBTRACTION VALUE BUT SUB DOES IT)  EXECUTE AL-CL TO AFFECT THE FLAG
     JG AL_IS_BIG 
     
     MOV DL,CL ;CL IS GREATER SEND ITTO PRINT
     MOV AH,2
     INT 21H ;DISPLAY
     JMP EXIT
    
    
    AL_IS_BIG:
        MOV DL,AL;AL IS GREATER SEND IT TO DL TO PRINT
        MOV AH,2
        INT 21H ;DISPLAY
  EXIT:  
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN