.MODEL SMALL
.STACK 100H
.DATA
MSG1 DB 'SHAKIB AL HASAN $'
MSG2 DB 'LIONEL MESSI $'
.CODE

MAIN PROC
    
    MOV AX,@DATA       ;INITIALISATION OF DATA SEGMENT
    MOV DS,AX
    
    LEA DX,MSG1
    MOV AH,9           ;LOAD EFFECTIVE ADDRESS
    INT 21H
    
    
    MOV AH,2
    MOV DL,0AH
    INT 21H            ;NEW LINE
    MOV DL,0DH
    INT 21H
    
    
    LEA DX,MSG2        ;LOAD EFFECTIVE ADDRESS
    MOV AH,9
    INT 21H
  
  EXIT:
  MOV AH,4CH
  INT 21H
  MAIN ENDP
END MAIN
    